name: pyaudio==0.2.14
on:
  workflow_dispatch:
jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: ./scripts/build_native_wheel.sh https://files.pythonhosted.org/packages/26/1d/8878c7752febb0f6716a7e1a52cb92ac98871c5aa522cba181878091607c/PyAudio-0.2.14.tar.gz
        env:
          CIBW_BEFORE_ALL_LINUX: curl -L https://github.com/PortAudio/portaudio/archive/refs/tags/v19.7.0.tar.gz | tar xzvf - && cd portaudio-19.7.0 && ./configure --enable-cxx && make install
          CIBW_BEFORE_ALL_MACOS: curl -L https://github.com/PortAudio/portaudio/archive/refs/tags/v19.7.0.tar.gz | tar xzvf - && cd portaudio-19.7.0 && ./configure --enable-cxx --disable-mac-universal && sudo make install && sudo cp include/pa_mac_core.h /usr/local/include/pa_mac_core.h
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""  # we're not build deps against an old enough deployment target, that's fine though
      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}
          path: ./wheelhouse/*.whl
